### ISSUE TITLE
OpenROAD-flow repository is gone!

### ISSUE THREAD

**Issue by kammoh** [The-OpenROAD-Project/OPENROAD_USERS_READ_ME_FIRST#1]
All of a sudden, the [OpenROAD-flow git repository](https://github.com/The-OpenROAD-Project/OpenROAD-flow.git) also referenced in the README here, is gone! No previous announcement or even mention of it, here or on Twitter! 
This abrupt deletion of a whole repository doesn't look good at all!

**Comment by rovinski** [comment]
We are aware of the issue and are working to resolve it as quickly as possible.

**Comment by kammoh** [comment]
Thanks

**Comment by rovinski** [comment]
A temporary read-only copy is now up at https://github.com/The-OpenROAD-Project/OpenROAD-flow

We are still working on getting the full history restored.

**Comment by tspyrou** [comment]
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts is the new location for the openroad flow. It is now public and fully up to date. -Tom
