### ISSUE TITLE
CMake Error due to missing LEMON

### ISSUE THREAD

**Issue by davehaglan** [The-OpenROAD-Project/OPENROAD_USERS_READ_ME_FIRST#3]
Hi,
I'm having trouble building OpenROAD from source following the instructions here:
https://openroad.readthedocs.io/en/latest/main/README.html

OS: Ubuntu 20.04.3 LTS

After syncing the GIT repository, I run the two scripts below as super user:
```
./etc/DependencyInstaller.sh -run
./etc/DependencyInstaller.sh -dev
```

Then I tried to use the build script:
`./etc/Build.sh`

The build script failed due to some missing packages below that I installed:
```
apt install swig
apt install libboost-all-dev
apt install libspdlog-dev
apt install libeigen3-dev
apt install lemon
```

I tried the build script again and it fails due to the missing LEMON package:
```
./etc/Build.sh
-- OpenROAD version: v2.0-1108-g2409932bc
-- System name: Linux
-- Compiler: GNU 9.3.0
-- Build type: RELEASE
-- Install prefix: /usr/local
-- TCL library: /usr/lib/aarch64-linux-gnu/libtcl.so
-- TCL header: /usr/include/tcl/tcl.h
-- TCL readline library: /usr/lib/aarch64-linux-gnu/libtclreadline.so
-- TCL readline header: /usr/include/aarch64-linux-gnu
-- spdlog: 1.5.0
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- STA version: 2.3.0
-- STA git sha: 85f437bc591aa8e3a5d83da7442d21f2530cfc5f
-- System name: Linux
-- Compiler: GNU 9.3.0
-- Build type: RELEASE
-- Build CXX_FLAGS: -O3 -DNDEBUG
-- Install prefix: /usr/local
-- TCL library: /usr/lib/aarch64-linux-gnu/libtcl.so
-- TCL header: /usr/include/tcl/tcl.h
-- SSTA: 0
-- STA executable: /home/ubuntu/OpenROAD/src/sta/app/sta
CMake Error at src/cts/src/CMakeLists.txt:38 (find_package):
  By not providing "FindLEMON.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LEMON", but
  CMake did not find one.

  Could not find a package configuration file provided by "LEMON" with any of
  the following names:

    LEMONConfig.cmake
    lemon-config.cmake

  Add the installation prefix of "LEMON" to CMAKE_PREFIX_PATH or set
  "LEMON_DIR" to a directory containing one of the above files.  If "LEMON"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/OpenROAD/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/OpenROAD/build/CMakeFiles/CMakeError.log".
```

I do have lemon installed but maybe its not configured correctly or not the right one?
```
> which lemon
/usr/bin/lemon
> lemon -x
Lemon version 1.0
```

Any help would be appreciated. Thanks!

**Comment by maliberty** [comment]
There are two different packages called lemon - one is a parser and the other a matrix library.  You want the later but I guess you have the former.  It is strange though as DependencyInstaller.sh should have taken care of it.  What platform are you running on?

**Comment by maliberty** [comment]
In the installer see
    lemonVersion=1.3.1
...
    if [[ -z $(grep "LEMON_VERSION \"${lemonVersion}\"" /usr/local/include/lemon/config.h) ]]; then
        cd "${baseDir}"
        wget http://lemon.cs.elte.hu/pub/sources/lemon-${lemonVersion}.tar.gz
        md5sum -c <(echo "e89f887559113b68657eca67cf3329b5  lemon-${lemonVersion}.tar.gz") || exit 1
        tar -xf lemon-${lemonVersion}.tar.gz
        cd lemon-${lemonVersion}
        cmake -B build .
        cmake --build build -j $(nproc) --target install
    else
        echo "Lemon already installed."
    fi

**Comment by vvbandeira** [comment]
@davehaglan please post here the output.log of
`sudo ./etc/DependencyInstaller.sh -dev 2>&1 | tee output.log`

Also as Matt mentioned, there are two "lemons". The one we required is a library so I don't think it has a bin/executable you can run `lemon -x` to get the version.

**Comment by davehaglan** [comment]
Thanks for the quick responses.  I see that I have the wrong lemon.

I'm running Ubuntu 20.04.03 on a rpi4.

After removing the wrong lemon, the results of the dependency script are below:
```
> sudo ./etc/DependencyInstaller.sh -dev 2>&1 | tee output.log
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
Hit:2 https://deb.nodesource.com/node_15.x focal InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Hit:5 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
tzdata is already the newest version (2021a-0ubuntu0.20.04).
The following package was automatically installed and is no longer required:
  libllvm11
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
libtcl8.6 is already the newest version (8.6.10+dfsg-1).
qt5-default is already the newest version (5.12.8+dfsg-0ubuntu1).
tcl-tclreadline is already the newest version (2.3.8-1).
binutils is already the newest version (2.34-6ubuntu1.1).
libgomp1 is already the newest version (10.3.0-1ubuntu1~20.04).
libpython3.8 is already the newest version (3.8.10-0ubuntu1~20.04).
The following package was automatically installed and is no longer required:
  libllvm11
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.
strip: '/usr/lib/x86_64-linux-gnu/libQt5Core.so': No such file
```
I searched for the lemon package in the Ubuntu package list and its not there:
https://packages.ubuntu.com/focal/allpackages

I tried to build from source with the instructions on, https://lemon.cs.elte.hu/trac/lemon/wiki/InstallLinux, and ran into a few more missing packages.  After installing glpk-utils, libglpk-dev, doxygen I still have three missing packages.

...
-- Could NOT find ILOG (missing: ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR) 
-- Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
-- Could NOT find SOPLEX (missing: SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR) 
...

I searched the Ubuntu package page for the missing packages and didn't find any that seemed like a good match.  Any ideas?

So not to be stopped I went ahead with the make and installed lemon-1.3.1.  (the self test aborted 1 of 44 tests)

The './etc/Build.sh' build script is running now.  I'll comment again if the build is successful.

Thanks,
Dave

**Comment by davehaglan** [comment]
The make install was successful.
